.github/workflows/dotnet-desktop.yml
=> Create dotnet workflow yaml : dotnet-desktop.yml

Frontend/src/AboutUsPage.tsx, Frontend/src/App.tsx, Frontend/src/FAQsPage.tsx, Frontend/src/Frontend.css, Frontend/src/ImpressumPage.tsx, Frontend/src/LandingPage.tsx
- added functionality and created an own class for each of the link-elements { FAQ's, About, Impressum } on LandingPage.tsx
- _new classes:_ 
AboutUsPage.tsx
FAQsPage.tsx
ImpressumPage.tsx
- _function:_
when you click on a link you get redirected to the specific url of the element
=> Added functionality to link-elements on LandingPage.tsx

Backend/API/Program.cs, Frontend/package-lock.json, Frontend/src/AboutUsPage.tsx, Frontend/src/App.tsx, Frontend/src/FAQsPage.tsx, Frontend/src/Frontend.css, Frontend/src/ImpressumPage.tsx, Frontend/src/LandingPage.tsx
Created the FAQ's page and added some questions (snapshot)
=> Frontend faqs page

Frontend/src/AboutUsPage.tsx, Frontend/src/Frontend.css
- added command to remove bullet points for links-block on AboutUsPage.tsx
- adjusted size of Team_Roles.png to fit on 100% browser zoom
- added "/" to href of links to fix commit warnings
- added Font specification to fix commit warning
=> - Added Link to LandingPage "Welcome"

Frontend/src/AboutUsPage.tsx, Frontend/src/FAQsPage.tsx, Frontend/src/Frontend.css, Frontend/src/ImpressumPage.tsx
Added LandingPage link and bugfixes
=> Frontend impressum page update

Frontend/src/AboutUsPage.tsx, Frontend/src/FAQsPage.tsx, Frontend/src/Frontend.css, Frontend/src/ImpressumPage.tsx, Frontend/src/LoginPage.tsx
- Created loginPage
- added logo & loginText
- added labels (name, pw)
- added button (submit)
- added link (sign up)
- added links to other pages (welcome, impressum, about us, FAQs)
=> Frontend login page

Frontend/src/Frontend.css, Frontend/src/LandingPage.tsx
- removed the 3 food images on landing page
- sized up Carlos as only shown image on landing page now
=> reduced images on landing page to Carlos

Frontend/package-lock.json, Frontend/package.json, Frontend/src/App.tsx, Frontend/src/components/AboutUsPage.tsx, Frontend/src/components/ButtonAppBar.tsx, Frontend/src/components/FAQsPage.tsx, Frontend/src/components/ImpressumPage.tsx, Frontend/src/components/LandingPage.tsx, Frontend/src/components/Logout.tsx, Frontend/src/components/MenuListComposition.tsx, Frontend/src/components/MyAccount.tsx, Frontend/src/design/AboutUsPage.css, Frontend/src/design/ButtonAppBar.css, Frontend/src/design/FAQs.css, Frontend/src/design/ImpressumPage.css, Frontend/src/design/LandingPage.css, package-lock.json, package.json
// **Global Navbar** //
-> created a Navbar/Header which  is tend to be placed on every page after succesfully logged in
-> linked all existing pages so far
-> added a menu button which opens a popup menu with settings, profile, account and logout
// **Bugs** //
-> after opened menu popup the  <ClickAwayListener> only respond when clicking near the popup => it should be respond everywhere in the browser area
// **Optimizations** //
-> several optimizations of pages & css
=> Implemented Global Navbar / Several Optimizations 

Backend/API/Controllers/LoginController.cs, Backend/API/Program.cs, Backend/DataAccess/DataAccess.cs, Backend/DataAccess/Entities/Authentication.cs, Backend/DataAccess/Entities/Ingredient.cs, Backend/DataAccess/Entities/Recipe.cs, Backend/DataAccess/Entities/User.cs, Backend/DataAccess/Mapping/AuthenticationMap.cs, Backend/DataAccess/Mapping/IngredientMap.cs, Backend/DataAccess/Mapping/RecipeMap.cs, Backend/DataAccess/Mapping/UserMap.cs, Backend/DataAccess/Repository/AuthenticationRepository.cs, Backend/DataAccess/Repository/IRepository.cs, Backend/DataAccess/Repository/RecipeRepository.cs, Backend/DataAccess/Repository/UserRepository.cs, Backend/Services/IngredientService.cs, Backend/Services/RecipeService.cs, Backend/Services/UserService.cs, Backend/Tests/UserRepositoryTests.cs
Issue https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=58676438
=> Implement database schema

Backend/DataAccess/Mapping/RecipeMap.cs, Backend/DataAccess/Mapping/UserMap.cs
Bug issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=59532006
=> fix n:m mappings

Backend/API/Controllers/RecipeController.cs, Backend/DataAccess/Mapping/RecipeMap.cs, Backend/Services/RecipeService.cs
You are now able to add a new recipe **BUT** you have to add an existing User to the recipe with an "email", "passwordhash", "name" and "profilePicture"
You can also delete Recipes by ID
=> Backend api post & delete endpoints recipe

Frontend/src/pages/MyRecipes.tsx, Frontend/src/style/MyRecipes.css
-> Redesign structure elements
=> // MyRecipes

Backend/API/Controllers/RecipeController.cs, Backend/API/Program.cs, Backend/DataAccess/Entities/Recipe.cs, Backend/DataAccess/Mapping/RecipeMap.cs, Backend/DataAccess/Repository/IRecipeRepository.cs, Backend/DataAccess/Repository/RecipeRepository.cs, Backend/Services/RecipeService.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=60388015
=> Create top recipes endpoint

Frontend/src/clients/RecipeClient.ts, Frontend/src/pages/MyRecipes.tsx, Frontend/src/style/MyRecipes.css
It is now possible to adventurize the recipe. The styling is missing, i'm leaving this part for stefan 😄. Regenerate also works but saving needs improvement.
=> added functionality to adventurize button

Frontend/src/App.tsx, Frontend/src/pages/MyRecipes.tsx, Frontend/src/pages/SignUp.tsx, Frontend/src/style/SignUp.css
-> created SignUp page
-> linked SignUp page in App.tsx
-> created form with username, email,password, repeat password field and submit button -> inserted Carlos with speech bubble to guide user
=> // Frontend: created SignUp page

Frontend/src/pages/MyRecipes.tsx, Frontend/src/pages/Settings.tsx, Frontend/src/style/ImageUploader.css, Frontend/src/style/Settings.css
=> // Settings

Backend/API/Controllers/LoginController.cs, Backend/API/Models/LoginDataModel.cs, Backend/API/Models/RegisterDataModel.cs, Backend/API/Program.cs, Backend/DataAccess/Entities/User.cs, Backend/Services/CryptoService.cs, Backend/Services/UserService.cs, Backend/Tests/ApiTests/LoginControllerTests.cs, Backend/Tests/Tests.cs, Backend/Tests/Tests.csproj, Backend/Tests/UserRepositoryTests.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=62527131
Requests edited:
- LogIn
Requests added:
- LogOut
- IsLoggedIn
- Register
Regexes used to validate register data:
- Username: `[A-Za-z0-9_]{4,16}`
- Email: `[\w-\.]+@([\w-]+\.)+[\w-]{2,24}` (found somewhere in the internet)
- Password: `(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,32}` (found on stack overflow)
Also added hashing of passwords
=> Backend: MEGA UPDATE 3.1 - Marc Edition: Implement user authentication (and a lot more)

Backend/API/Program.cs, Backend/DataAccess/DataAccess.csproj, Backend/DataAccess/Entities/Recipe.cs, Backend/DataAccess/Entities/User.cs, Backend/DataAccess/Mapping/RecipeMap.cs, Backend/DataAccess/Mapping/UserMap.cs, Backend/DataAccess/Repository/IUserRepository.cs, Backend/DataAccess/Repository/UserRepository.cs, Backend/Services/RecipeService.cs, Backend/Services/UserService.cs, Backend/Tests/UserRepositoryTests.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=62544721
- This changes database mappings, therefore everyone has to reset their database again
- @FrontendTeam please check if this breaks the frontend, bc attributes of recipe where changed (CreatorEmail -> CreatorId, LikedEmails -> LikedUserIds)
=> Backend: change primary key of user entity

package-lock.json, package.json
-> Setup Selenium
-> Updated chrome and firefox webdriver
-> See instruction in [wiki](https://github.com/SE-TINF22B6/CookHub/wiki/Testing)
=> Testing: Selenium: Setup

Backend/API/Controllers/RecipeController.cs, Backend/API/Models/AdventureModel.cs, Backend/Services/RecipeService.cs, Backend/Tests/ApiTests/RecipeControllerTests.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=62759576
=> Backend: Make adventure text savable

Frontend/src/pages/Welcome.tsx, Frontend/src/style/Welcome.css
-> Elements are related to zoom now
-> Page is now responsive for PC, Tablet and Mobile
-> replaced all MaterialUI components
-> cleaned up tsx and css code
=> //LandingPage

Frontend/src/components/NavBar.tsx, Frontend/src/pages/Welcome.tsx, Frontend/src/style/NavBar.css, Frontend/src/style/Welcome.css
-> NavBar is now responsiv and switches to mobile view when width < 1100px
=> // Frontend nav bar responsivication

Backend/API/Program.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=63717659
=> Backend: Fix logout not working

Frontend/src/pages/Login.tsx, Frontend/src/style/Login.css, Frontend/src/style/NavBar.css
//NavBar
-> fixed wrong size change of animated logo
//Login
-> Login page is now responsive
=> Frontend: LoginPage: responsification & NavBar: small bugfix

Frontend/src/App.tsx, Frontend/src/components/NavBar.tsx, Frontend/src/components/NotLoggedIn.tsx, Frontend/src/models/UserData.ts, Frontend/src/models/UserDataParams.ts, Frontend/src/pages/FoodForge.tsx, Frontend/src/pages/Login.tsx, Frontend/src/pages/Profile.tsx, Frontend/src/pages/Settings.tsx
fixed log out bug on firefox
created new NotLoggedIn Component
=> redesigned login functionality

Frontend/src/App.tsx, Frontend/src/components/NavBar.tsx, Frontend/src/pages/FindRecipes.tsx, Frontend/src/style/FindRecipes.css
-> default show top recipes is now responsive
-> Ribbons not yet
-> small design changes
=> // Frontend: FindRecipe: 1/2 responsificated

Backend/Services/UserService.cs, Backend/Tests/ApiTests/LoginControllerTests.cs, Frontend/src/clients/UserClient.ts, Frontend/src/pages/SignUp.tsx
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=62326851
=> Connect endpoint for sign up

Frontend/src/pages/FindRecipes.tsx, Frontend/src/style/FindRecipes.css
-> page is now responsive
-> excluded dome elements to be showed in mobile view
=> // FindRecipe

Backend/API/Controllers/UserController.cs, Backend/API/Models/PasswordChangeModel.cs, Backend/Contracts/Entities/Recipe.cs, Backend/Contracts/Entities/User.cs, Backend/DataAccess/Mapping/RecipeMap.cs, Backend/DataAccess/Mapping/UserMap.cs, Backend/DataAccess/Repository/UserRepository.cs, Backend/Services/RecipeService.cs, Backend/Services/UserService.cs, Backend/Tests/ApiTests/LoginControllerTests.cs, Backend/Tests/ApiTests/UserControllerTests.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=64791602
Requests added:
- ChangeUsername
- ChangePassword
- DeleteAccount
- ChangeProfilePicture
+ tests
=> Backend: Create requests for user settings page

Frontend/src/App.test.tsx, Frontend/src/clients/UserClient.ts, Frontend/src/components/InfoTable.tsx, Frontend/src/pages/FindRecipes.tsx, Frontend/src/pages/Login.tsx, Frontend/src/pages/MyRecipes.tsx, Frontend/src/pages/SignUp.tsx, Frontend/src/setupTests.ts, Frontend/src/tests/App.test.tsx, Frontend/src/tests/FindRecipes.test.tsx, Frontend/src/tests/Login.test.tsx, Frontend/src/tests/MyRecipes.test.tsx, Frontend/src/tests/Recipe.test.tsx, Frontend/src/tests/SignUp.test.tsx
=> Frontend: add more selenium tests

Frontend/src/pages/Profile.tsx, Frontend/src/style/Profile.css
=> // Frontend: Profile: Responsification

Frontend/src/pages/Profile.tsx, Frontend/src/pages/Settings.tsx, Frontend/src/style/ImageUploader.css, Frontend/src/style/Profile.css, Frontend/src/style/Settings.css
// Settings
-> is now responsive
-> small design changes
-> added info button
-> added current password text field which will be checked when the user tries to delete his account (Mock Password)
-> added popup to inform user if the password for deletion is incorrect
-> added confirmation popup when password for deletion is correct
// Image Uploader
-> added media query for the component
=> // Frontend: Settings: Responsification, Design and Functionality

Frontend/src/clients/UserClient.ts, Frontend/src/components/ImageUploader.tsx, Frontend/src/pages/Settings.tsx
=> Username is now instantly displayed after changing it,

Backend/API/Controllers/UserController.cs, Backend/Services/UserService.cs, Backend/Tests/ApiTests/UserControllerTests.cs
Added endpoints for:
adding viewed Recipe to History of logged in User
&
providing a List of the History of a User
+
Tests
=> Backend add view recipe endpoint

Backend/API/Controllers/UserController.cs, Backend/Tests/ApiTests/UserControllerTests.cs
Issue: https://github.com/orgs/SE-TINF22B6/projects/16/views/1?pane=issue&itemId=64791862
=> Backend: create missing endpoint for profile page

Frontend/src/components/NavBar.tsx
Also did minimal code refactoring
=> Logo now redirects to FindRecipes Page when logged in

Frontend/src/pages/FoodForge.tsx, Frontend/src/style/FoodForge.css
-> design adjustments
-> is now responsive (except input fields from AddIngredientApp
=> // Frontend: FoodForge: Responsification

Frontend/src/pages/Settings.tsx, Frontend/src/setupTests.ts, Frontend/src/tests/App.test.tsx, Frontend/src/tests/Settings.test.tsx
=> Frontend: add tests for settings page und so

Frontend/src/pages/MyRecipes.tsx, Frontend/src/style/MyRecipes.css
I can't adventurize recipes because I never added the OpenAI key and dont know where it is
So I dont know how the generated text looks like
=> added styling to adventurize it

Backend/API/Controllers/RecipeController.cs, Backend/Services/RecipeService.cs, Frontend/src/clients/RecipeClient.ts, Frontend/src/pages/FindRecipes.tsx, Frontend/src/pages/MyRecipes.tsx, Frontend/src/style/FindRecipes.css, Frontend/src/tests/FindRecipes.test.tsx
+ search for category + display (clickable) categories
+ search for ingredient
=> Backend, Frontend: Search for categories and display categories on recipes

Frontend/src/pages/Settings.tsx
-> fixed help button color
// FoodForge
-> fixed main-container height displaying  a blue bar at the bottom
// Settings
-> Fixed pop up color
=> // AboutUs
